# Generated by Django 3.1.14 on 2022-08-14 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220814_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[(1, 'Tops'), (2, 'Bottoms'), (3, 'Otro')], max_length=200),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.stage'),
        ),
    ]
