# Generated by Django 3.1.14 on 2022-08-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220814_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.IntegerField(choices=[(1, 'Tops'), (2, 'Bottoms'), (3, 'Otro')], default=3),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
