# Generated by Django 3.1.14 on 2022-08-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220814_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='stage',
            field=models.IntegerField(choices=[(1, 'stage-1'), (2, 'stage-2'), (3, 'stage-3'), (4, 'stage-4')], default=1),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
